### ISSUE TITLE
你好作者这个怎么跑不起来

### ISSUE THREAD

**Issue by lyh2606179909** [zoutao98/chatgpt-wx#1]
你好作者这个怎么跑不起来

**Comment by zoutao98** [comment]
会python吗，什么问题描述下，有按照readme使用吗，PC挂了科学全局吗，下次麻烦问问题先百度下“如何问好一个问题”。我自己跑是没出现问题

**Comment by lyh2606179909** [comment]
> 会python吗，什么问题描述下，有按照readme使用吗，PC挂了科学全局吗，下次麻烦问问题先百度下“如何问好一个问题”。我自己跑是没出现问题

是的挂了科学全局，然后会python，代码运行一段时间被自动退出了
![1679366171611](https://user-images.githubusercontent.com/31297917/226505839-ee8bb423-0832-4e9e-9be6-38fb9096a001.png)
![1679366194451](https://user-images.githubusercontent.com/31297917/226505860-6914441f-8ac5-421f-98a1-3421ba48979b.png)
dll是注入了，你看一下http调用

**Comment by zoutao98** [comment]
> > 会python吗，什么问题描述下，有按照readme使用吗，PC挂了科学全局吗，下次麻烦问问题先百度下“如何问好一个问题”。我自己跑是没出现问题
> 
> 是的挂了科学全局，然后会python，代码运行一段时间被自动退出了 ![1679366171611](https://user-images.githubusercontent.com/31297917/226505839-ee8bb423-0832-4e9e-9be6-38fb9096a001.png) ![1679366194451](https://user-images.githubusercontent.com/31297917/226505860-6914441f-8ac5-421f-98a1-3421ba48979b.png) dll是注入了，你看一下http调用

![图片](https://user-images.githubusercontent.com/46660687/226506412-24136ea3-e17a-4667-bfe8-8298a69831c2.png)
我这边没有问题，关于dll的问题你要去访问我的感谢里面的那个仓库，我是从他哪里搞过来的

**Comment by lyh2606179909** [comment]
好的谢谢你的回复
